version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      frontend-npm:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      backend-python:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/collector"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      collector-python:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      backend-container:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/collector"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      collector-container:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      frontend-container:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      compose-images:
        patterns:
          - "*"
